<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ReportesNotas\InformeNotas.rdlc" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ReportesNotas\InformeNotas.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="ReportViewerCore.NETCore" Version="15.1.27" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CapaDatos\CapaDatos.csproj" />
    <ProjectReference Include="..\CapaEntidad\CapaEntidad.csproj" />
    <ProjectReference Include="..\CapaNegocio\CapaNegocio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ProyectoNotasBDDataSet.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ProyectoNotasBDDataSet.xsd</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="ProyectoNotasBDDataSet.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>ProyectoNotasBDDataSet.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>